"""Dados iniciais (seed) do modulo Comercializacao. Modulo SEM dependencias:
importado tanto pela migration quanto pelo comando `flask init-db`.

PRODUTOS_VENDA: nome na planilha -> (descricao usada na busca do portal, id do produto no portal)
ESTADOS: UF -> indice da opcao no select de UF do portal (0 = placeholder)
"""
ESTADOS = [
    ('AC', 1),
    ('AL', 2),
    ('AM', 3),
    ('AP', 4),
    ('BA', 5),
    ('CE', 6),
    ('DF', 7),
    ('ES', 8),
    ('GO', 9),
    ('MA', 10),
    ('MG', 11),
    ('MS', 12),
    ('MT', 13),
    ('PA', 14),
    ('PB', 15),
    ('PE', 16),
    ('PI', 17),
    ('PR', 18),
    ('RJ', 19),
    ('RN', 20),
    ('RO', 21),
    ('RR', 22),
    ('RS', 23),
    ('SC', 24),
    ('SE', 25),
    ('SP', 26),
    ('TO', 27),
]

PRODUTOS_VENDA = [
    ('APRESUNTADO RESFRIADO', 'Apresuntado', 17178),
    ('APRESUNTADO RESFRIADO FATIADO', 'Apresuntado', 17176),
    ('BACON', 'Bacon', 17189),
    ('BACON RESFRIADO FATIADO', 'Bacon', 17186),
    ('CARNE CONGELADA DE SUINO COM OSSO', 'Carne congelada de suino com osso', 17344),
    ('CARNE CONGELADA DE SUINO SEM OSSO', 'Carne congelada de suino sem osso', 17347),
    ('CARNE DEFUMADA DE SUÍNO COM OSSO', 'Carne defumada de suino com osso', 17486),
    ('CARNE MOIDA CONGELADA', 'Carne moida congelada de suino', 36031),
    ('CARNE RESFRIADA DE SUINO COM OSSO', 'Carne resfriada de suino com osso', 17662),
    ('CARNE RESFRIADA DE SUINO SEM OSSO', 'Carne resfriada de suino sem osso', 17665),
    ('CARNE SALGADA DE SUINO COM OSSO', 'Carne salgada de suino com osso', 17760),
    ('CARNE TEMPERADA CONGELADA DE SUINO SEM OSSO', 'Carne temperada congelada de suino sem osso', 17820),
    ('CARNE TEMPERADA RESFRIADA DE SUINO SEM OSSO', 'Carne temperada resfriada de suino sem osso', 17953),
    ('CERDAS DE SUINOS', 'Cerdas de suino', 17971),
    ('ESPINHACO CONGELADO DE SUINO', 'Ossos congelados de suino', 18398),
    ('ENVOLTORIO NATURAL DE SUINO CONGELADO (RETO)', 'envoltorios naturais congelados de suino', 18035),
    ('GRAXA BRANCA', 'Graxa branca', 18102),
    ('LANCHE RESFRIADO', 'Fiambre', 18082),
    ('LINGUICA CALABRESA CONGELADA', 'Linguica cozida', 18140),
    ('LINGUICA CALABRESA RESFRIADA', 'Linguica cozida', 18141),
    ('LINGUICA CALABRESA TEMPERATURA AMBIENTE', 'Linguica cozida', 35359),
    ('LINGUICA FRESCAL CONGELADA', 'Linguica frescal', 18152),
    ('LINGUICA FRESCAL RESFRIADA', 'Linguica frescal', 18154),
    ('LINGUICA TOSCANA CONGELADA', 'Linguica frescal', 18152),
    ('LINGUICA TOSCANA RESFRIADA', 'Linguica frescal', 18154),
    ('MASCARA CONGELADA', 'Miudos congelados de suino', 18200),
    ('MASCARA SALGADA DE SUINO', 'Miudos salgados de suino', 18321),
    ('MIUDO SALGADO DE SUINO (GARGANTA)', 'Miudos salgados de suino', 18321),
    ('MIUDOS CONGELADOS DE SUINO', 'Miudos congelados de suino', 18200),
    ('MIUDOS COZIDOS CONGELADO', 'miudos cozidos congelados de suino', 18215),
    ('MIUDOS RESFRIADOS DE SUINO', 'Miudos resfriados de suino', 18285),
    ('MIUDOS SALGADOS', 'Miudos salgados de suino', 18321),
    ('MORTADELA AMBIENTE', 'Mortadela', 18382),
    ('MORTADELA RESFRIADA', 'Mortadela', 18384),
    ('MORTADELA RESFRIADA FATIADA', 'Mortadela', 18378),
    ('MUCOSA INTESTINAL DE SUINOS', 'Mucosa do intestino de suino', 18390),
    ('OSSOS IN NATURA DE SUINOS', 'Residuos de abate de suino', 18538),
    ('OSSOS RESFRIADOS', 'Ossos resfriados de suino', 18402),
    ('PAPADA CONGELADA', 'Papada congelada de suino', 18421),
    ('PATE DE GALINHA', 'Pate de galinha', 18425),
    ('PATE DE PRESUNTO', 'Pate de suino', 18438),
    ('PELE CONGELADA DE SUINO', 'Pele congelada de suino', 18443),
    ('PRESUNTO RESFRIADO', 'Presunto cozido', 18497),
    ('PRESUNTO RESFRIADO FATIADO', 'Presunto cozido', 18495),
    ('RESIDUOS DE ABATE DE SUINOS', 'Residuos de abate de suino', 18538),
    ('SALAME', 'Salame', 18543),
    ('SALAME RESFRIADO FATIADO', 'Salame', 35424),
    ('SALSICHA RESFRIADA', 'Salsicha resfriada', 18553),
    ('SANGUE DE SUINOS', 'Sangue de suino', 35766),
    ('TOUCINHO CONGELADO DE SUINO', 'toucinho congelado de suino', 18598),
    ('TOUCINHO RESFRIADO DE SUINO', 'TOUCINHO RESFRIADO DE SUÍNO', 18599),
]


# codigo, nome, tipo_transacao_idx, ambito_idx, operador_idx, rotulo no portal
# So "venda" vem pronto (indices do fluxo legado). Recebimento/expedicao sao cadastrados
# em Admin > Constantes > Tipos de lancamento quando o layout for definido.
TIPOS_LANCAMENTO = [
    ('venda', 'Venda', 1, 1, 2, 'Venda'),
]
