"""empty message

Revision ID: 05dd8bffec51
Revises: 1fd41d5d898c
Create Date: 2025-11-19 16:58:36.108414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dd8bffec51'
down_revision = '1fd41d5d898c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               server_default='USER',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'user'"),
               existing_nullable=False)

    # ### end Alembic commands ###
