"""add tabela mapa_credencial

Revision ID: 0e2b53c7a9c6
Revises: f0298dfc0059
Create Date: 2025-10-20 16:09:08.658351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2b53c7a9c6'
down_revision = 'f0298dfc0059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapa_credencial_owner'))
        batch_op.drop_constraint(batch_op.f('uq_user_sif_especie'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_mapa_credencial_owner_user_id'), ['owner_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mapa_credencial_owner_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_sif_especie'), ['owner_user_id', 'numero_sif', 'especie'])
        batch_op.create_index(batch_op.f('ix_mapa_credencial_owner'), ['owner_user_id'], unique=False)

    # ### end Alembic commands ###
