"""empty message

Revision ID: 17e3eb49baba
Revises: c792d8f600dc
Create Date: 2025-12-03 10:58:14.940570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e3eb49baba'
down_revision = 'c792d8f600dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=20), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('recurso',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.alter_column('recurso',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'web'"),
               existing_nullable=False)

    op.drop_table('workers')
    # ### end Alembic commands ###
