"""baseline

Revision ID: 3c208875e395
Revises: 
Create Date: 2025-10-09 09:52:20.942774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c208875e395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # A baseline so ALTERA um banco que ja tem as tabelas (o historico antigo nao as cria).
    # Em banco NOVO use `flask init-db`: cria o schema, carrega as constantes e marca as migrations.
    if not sa.inspect(op.get_bind()).has_table('empresa'):
        raise RuntimeError(
            "Banco vazio: as migrations nao criam o schema do zero. "
            "Rode `flask init-db` (banco novo) em vez de `flask db upgrade`. "
            "Use `flask db upgrade` apenas em um banco que ja existe (ex.: o db.sqlite antigo)."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_cnpj'), ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_empresa_cnpj'), type_='unique')

    # ### end Alembic commands ###
