"""add credencial validado validate_at last_error

Revision ID: 3cb14d62d49e
Revises: e82eb3da731a
Create Date: 2025-10-21 17:52:04.978321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb14d62d49e'
down_revision = 'e82eb3da731a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validado', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_error', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.drop_column('last_error')
        batch_op.drop_column('validado')

    # ### end Alembic commands ###
