"""Novas tabelas temp

Revision ID: 61b3209f7c85
Revises: 3c208875e395
Create Date: 2025-10-10 10:22:20.472584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b3209f7c85'
down_revision = '3c208875e395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dif_tmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATED', 'INVALID', 'PROCESSED', name='upload_status'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_dif_tmp_registro_id_registro')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuario.id'], name=op.f('fk_dif_tmp_uploaded_by_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dif_tmp'))
    )
    op.create_table('gta_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATED', 'INVALID', 'PROCESSED', name='upload_status'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_gta_temp_registro_id_registro')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuario.id'], name=op.f('fk_gta_temp_uploaded_by_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gta_temp'))
    )
    op.create_table('sif_tmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATED', 'INVALID', 'PROCESSED', name='upload_status'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_sif_tmp_registro_id_registro')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuario.id'], name=op.f('fk_sif_tmp_uploaded_by_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sif_tmp'))
    )
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelo_tipo_nome'))

    op.drop_table('modelo')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_cnpj'), ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_empresa_cnpj'), type_='unique')

    op.create_table('modelo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('gta_range', sa.VARCHAR(length=128), nullable=True),
    sa.Column('dif_range', sa.VARCHAR(length=128), nullable=True),
    sa.Column('condenas_range', sa.VARCHAR(length=128), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelo_tipo_nome'), ['tipo', 'nome'], unique=False)

    op.drop_table('sif_tmp')
    op.drop_table('gta_temp')
    op.drop_table('dif_tmp')
    # ### end Alembic commands ###
