"""fix tmp mixin rel/user + class order + rename gta staging

Revision ID: 6706974f67d0
Revises: 61b3209f7c85
Create Date: 2025-10-10 10:47:41.038525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6706974f67d0'
down_revision = '61b3209f7c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gta_upload_tmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATED', 'INVALID', 'PROCESSED', name='upload_status'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_gta_upload_tmp_registro_id_registro')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuario.id'], name=op.f('fk_gta_upload_tmp_uploaded_by_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gta_upload_tmp'))
    )
    op.drop_table('gta_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gta_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('registro_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('model', sa.VARCHAR(length=64), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_gta_temp_registro_id_registro')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuario.id'], name=op.f('fk_gta_temp_uploaded_by_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gta_temp'))
    )
    op.drop_table('gta_upload_tmp')
    # ### end Alembic commands ###
