"""empty message

Revision ID: 714ff0b8a088
Revises: 17e3eb49baba
Create Date: 2025-12-03 17:15:57.827115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714ff0b8a088'
down_revision = '17e3eb49baba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=13), nullable=False))

    # ### end Alembic commands ###
