"""add tabela mapa_credencial com validate

Revision ID: b3d98862a2ff
Revises: 0e2b53c7a9c6
Create Date: 2025-10-20 16:44:51.560059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d98862a2ff'
down_revision = '0e2b53c7a9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validate_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.drop_column('validate_at')

    # ### end Alembic commands ###
