"""empty message

Revision ID: c792d8f600dc
Revises: 05dd8bffec51
Create Date: 2025-12-03 09:12:02.561180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c792d8f600dc'
down_revision = '05dd8bffec51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
               batch_op.add_column(
            sa.Column(
                'recurso',
                sa.String(length=16),
                nullable=False,
                server_default="web"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('recurso')

    # ### end Alembic commands ###
