"""exec_job table

Revision ID: e82eb3da731a
Revises: b3d98862a2ff
Create Date: 2025-10-21 16:36:44.471954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e82eb3da731a'
down_revision = 'b3d98862a2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exec_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('gta_source', sa.String(length=16), nullable=False),
    sa.Column('commands', sqlite.JSON(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('errors', sqlite.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['usuario.id'], name=op.f('fk_exec_job_owner_user_id_usuario'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registro_id'], ['registro.id'], name=op.f('fk_exec_job_registro_id_registro'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exec_job'))
    )
    with op.batch_alter_table('exec_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exec_job_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exec_job_registro_id'), ['registro_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exec_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exec_job_registro_id'))
        batch_op.drop_index(batch_op.f('ix_exec_job_owner_user_id'))

    op.drop_table('exec_job')
    # ### end Alembic commands ###
