"""add tabela mapa_credencial

Revision ID: f0298dfc0059
Revises: f5ca0f129a36
Create Date: 2025-10-20 15:40:37.667874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0298dfc0059'
down_revision = 'f5ca0f129a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapa_credencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('usuario_app', sa.String(length=100), nullable=False),
    sa.Column('senha_enc', sa.LargeBinary(), nullable=False),
    sa.Column('numero_sif', sa.String(length=20), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['usuario.id'], name=op.f('fk_mapa_credencial_owner_user_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapa_credencial')),
    sa.UniqueConstraint('owner_user_id', 'numero_sif', 'especie', name='uq_user_sif_especie')
    )
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.create_index('ix_mapa_credencial_owner', ['owner_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_credencial', schema=None) as batch_op:
        batch_op.drop_index('ix_mapa_credencial_owner')

    op.drop_table('mapa_credencial')
    # ### end Alembic commands ###
