"""ajuste nas relacoes de uploads e registrs

Revision ID: f5ca0f129a36
Revises: 56df1a67c957
Create Date: 2025-10-15 09:33:11.564027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ca0f129a36'
down_revision = '56df1a67c957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dif_tmp', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_dif_tmp_registro_id'), ['registro_id'], unique=False)
        batch_op.create_unique_constraint('uq_dif_registro', ['registro_id'])
        batch_op.drop_constraint(batch_op.f('fk_dif_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dif_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gta_upload_tmp', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_gta_upload_tmp_registro_id'), ['registro_id'], unique=False)
        batch_op.create_unique_constraint('uq_gta_upload_registro', ['registro_id'])
        batch_op.drop_constraint(batch_op.f('fk_gta_upload_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gta_upload_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sif_tmp', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_sif_tmp_registro_id'), ['registro_id'], unique=False)
        batch_op.create_unique_constraint('uq_sif_registro', ['registro_id'])
        batch_op.drop_constraint(batch_op.f('fk_sif_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sif_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sif_tmp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sif_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sif_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'])
        batch_op.drop_constraint('uq_sif_registro', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sif_tmp_registro_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('gta_upload_tmp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gta_upload_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gta_upload_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'])
        batch_op.drop_constraint('uq_gta_upload_registro', type_='unique')
        batch_op.drop_index(batch_op.f('ix_gta_upload_tmp_registro_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('dif_tmp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dif_tmp_registro_id_registro'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dif_tmp_registro_id_registro'), 'registro', ['registro_id'], ['id'])
        batch_op.drop_constraint('uq_dif_registro', type_='unique')
        batch_op.drop_index(batch_op.f('ix_dif_tmp_registro_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
